packages:
  - 'frontend'
  - 'backend'
  - 'packages/*'
allowBuilds:
  bcrypt: true
  '@prisma/client': true
  unrs-resolver: true
  '@nestjs/core': true
  esbuild: true
  prisma: true
  '@prisma/engines': true
  msgpackr-extract: true
